SELECT a.AUTHOR_ID, c.AUTHOR_NAME, a.CATEGORY, SUM((a.PRICE * b.TOTAL_SALES)) AS TOTAL_SALES
FROM BOOK AS a
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM
        BOOK_SALES
    WHERE YEAR(SALES_DATE) = "2022" and MONTH(SALES_DATE) = "01"
    GROUP BY BOOK_ID
) AS b
ON a.BOOK_ID = b.BOOK_ID
JOIN AUTHOR AS c
ON a.AUTHOR_ID = c.AUTHOR_ID
GROUP BY a.AUTHOR_ID, a.CATEGORY
ORDER BY a.AUTHOR_ID, a.CATEGORY DESC
