SELECT
    a.PRODUCT_CODE,
    SUM(b.SALES_AMOUNT) * a.PRICE AS SALES
FROM
    PRODUCT AS a
JOIN
    OFFLINE_SALE AS b
ON
    a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY
    a.PRODUCT_CODE
ORDER BY
    SALES DESC, a.PRODUCT_CODE