SELECT a.PRODUCT_CODE, SUM(PRICE * b.SALES_AMOUNT) AS SALES
FROM PRODUCT AS a
JOIN OFFLINE_SALE AS b
ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_ID
ORDER BY SUM(PRICE * SALES_AMOUNT) DESC, a.PRODUCT_CODE