WITH MOST AS (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM
        REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    limit 1
)

SELECT
    a.MEMBER_NAME,
    b.REVIEW_TEXT,
    DATE_FORMAT(b.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM
    MEMBER_PROFILE AS a
JOIN REST_REVIEW AS b
ON
    a.MEMBER_ID = b.MEMBER_ID
WHERE 
    a.MEMBER_ID = (SELECT MEMBER_ID FROM MOST)
ORDER BY REVIEW_DATE, REVIEW_TEXT