SELECT ID,
    CASE
        WHEN CHILD_COUNT is NULL THEN 0
        ELSE CHILD_COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA AS a
LEFT OUTER JOIN
    (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID is not NULL
    GROUP BY PARENT_ID) AS b
ON a.ID=b.PARENT_ID