SELECT
    b.ANIMAL_ID,
    b.NAME
FROM
    ANIMAL_INS AS a
RIGHT JOIN
    ANIMAL_OUTS AS b
ON
    a.ANIMAL_ID = b.ANIMAL_ID
WHERE
    b.DATETIME IS NOT NULL AND a.DATETIME IS NULL
ORDER BY
    ANIMAL_ID;