SELECT
    a.PRODUCT_ID,
    a.PRODUCT_NAME,
    (a.PRICE * b.TOTAL_AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS a
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM 
        FOOD_ORDER
    WHERE
        PRODUCE_DATE LIKE "%2022-05%"
    GROUP BY PRODUCT_ID
) AS b
ON
    a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID