SELECT a.USER_ID, a.NICKNAME, b.TOTAL_SALES
FROM 
    USED_GOODS_USER AS a
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AS b
ON
  a.USER_ID = b.WRITER_ID
ORDER BY
    b.TOTAL_SALES