-- 코드를 작성해주세요
SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_INFO AS c
WHERE c.ITEM_ID in 
    (SELECT b.ITEM_ID
    FROM ITEM_INFO AS a
    JOIN ITEM_TREE AS b
    ON a.ITEM_ID = b.PARENT_ITEM_ID
    WHERE a.RARITY='RARE')
ORDER BY c.ITEM_ID DESC;