SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM developers
WHERE SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'Py%')
OR SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'C#')
ORDER BY ID;