SELECT
    b.USER_ID,
    b.NICKNAME,
    CONCAT(b.CITY, " ", b.STREET_ADDRESS1, " ", b.STREET_ADDRESS2) AS "전체주소",
    CONCAT(
        SUBSTRING(b.TLNO, 1, 3), '-',
        SUBSTRING(b.TLNO, 4, 4), '-',
        SUBSTRING(b.TLNO, 8, 4)
    ) AS 전화번호
FROM
    USED_GOODS_BOARD AS a
JOIN
    USED_GOODS_USER AS b
ON
    a.WRITER_ID = b.USER_ID
GROUP BY
    a.WRITER_ID
HAVING
    COUNT(*) >= 3
ORDER BY
    a.WRITER_ID DESC;