-- 코드를 작성해주세요
SELECT
    SUM(B.SCORE) AS SCORE , A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM 
    HR_EMPLOYEES AS A
JOIN
    (SELECT *
    FROM 
        HR_GRADE
    WHERE
        YEAR = 2022) AS B
ON
    A.EMP_NO = B.EMP_NO
GROUP BY 
    A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
ORDER BY 
    SUM(SCORE) DESC
LIMIT 1;