SELECT b.SCORE, a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
FROM HR_EMPLOYEES AS a
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS b
on a.EMP_NO = b.EMP_NO
ORDER BY SCORE DESC
limit 1;
