SELECT
    a.DEPT_ID,
    a.DEPT_NAME_EN,
    b.AVG_SAL
FROM HR_DEPARTMENT AS a
JOIN (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM
        HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS b
ON
    a.DEPT_ID = b.DEPT_ID
ORDER BY b.AVG_SAL DESC