SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS a
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM
        BOOK_SALES
    WHERE SALES_DATE like '%2022-01%'
    GROUP BY BOOK_ID
) AS b 
ON a.BOOK_ID = b.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY

